-- CreateEnum
CREATE TYPE "MemberTier" AS ENUM ('MASTER_1000_PLUS', 'MASTER_800_1000', 'MASTER_600_800', 'MASTER_400_600', 'MASTER_200_400', 'MASTER_0_200', 'DIAMOND_1', 'DIAMOND_2', 'DIAMOND_3', 'DIAMOND_4', 'EMERALD_1', 'EMERALD_2', 'EMERALD_3', 'EMERALD_4', 'PLATINUM_1', 'PLATINUM_2', 'PLATINUM_3', 'PLATINUM_4', 'GOLD_1', 'GOLD_2', 'GOLD_3', 'GOLD_4', 'SILVER_1', 'SILVER_2', 'SILVER_3', 'SILVER_4', 'BRONZE_1', 'BRONZE_2', 'BRONZE_3', 'BRONZE_4', 'IRON', 'UNRANKED');

-- AlterTable
ALTER TABLE "Member" ADD COLUMN     "tier" "MemberTier" NOT NULL DEFAULT 'UNRANKED';
